"""Module 10 - Dash dashboard answering the research question: "Can the
price of a diamond be determined based upon its features?"

This single-page Dash application displays the three Seaborn visualizations
generated by visualization.py alongside a natively embedded, interactive
Plotly figure, together with a short guiding conclusion.

Usage:
    python dashboard.py --input diamonds.csv

Then open the printed local URL (default http://127.0.0.1:8050) in a
browser.
"""

import argparse
from dash import Dash, dcc, html

from visualization import (
    CLARITY_ORDER,
    COLOR_ORDER,
    CUT_ORDER,
    add_input_argument,
    build_animated_price_scatter_figure,
    clean_data,
    load_data,
)

RESEARCH_QUESTION = "Can the Price of a Diamond Be Determined Based Upon Its Features?"

IMG_STYLE = {
    "width": "100%",
    "maxWidth": "900px",
    "display": "block",
    "margin": "0 auto",
}

def _monotonic_grades(df) -> list:
    """Determine which quality grades show a monotonic price-per-carat trend.

    Computes mean price-per-carat for cut, color, and clarity from the
    actual data and checks each for a monotonic increase from worst to
    best grade, rather than assuming all three behave the same way.

    Args:
        df: Cleaned diamonds DataFrame.

    Returns:
        The subset of ["cut", "color", "clarity"] whose mean
        price-per-carat is strictly non-decreasing from worst to best
        grade in this dataset.
    """
    price_per_carat = df["price"] / df["carat"]
    grade_columns = {
        "cut": (df["cut"], CUT_ORDER),
        "color": (df["color"], COLOR_ORDER),
        "clarity": (df["clarity"], CLARITY_ORDER),
    }

    monotonic = []
    for name, (values, order) in grade_columns.items():
        means = price_per_carat.groupby(values, observed=True).mean().reindex(order)
        if means.is_monotonic_increasing:
            monotonic.append(name)
    return monotonic


def build_conclusion_text(df) -> str:
    """Build the guiding conclusion text, computing all claims live.

    Args:
        df: Cleaned diamonds DataFrame.

    Returns:
        The conclusion paragraph, with the carat/price correlation and
        the set of quality grades showing a monotonic price-per-carat
        premium both computed from the actual data rather than assumed.
    """
    carat_price_corr = df["carat"].corr(df["price"])
    monotonic = _monotonic_grades(df)

    if monotonic:
        grade_list = ", ".join(monotonic)
        verb = "shows" if len(monotonic) == 1 else "show"
        premium_clause = (
            f"Once price is normalized per carat, {grade_list} "
            f"{verb} a clear, monotonic price premium as quality improves"
        )
    else:
        premium_clause = (
            "Once price is normalized per carat, quality grade still "
            "shifts average price, though not in a strictly monotonic "
            "step from worst to best grade"
        )

    return (
        f"Carat weight is by far the strongest predictor of price "
        f"(r = {carat_price_corr:.2f}), and dominates the raw averages so "
        "heavily that lower-cut, larger stones can appear more expensive "
        f"on average than smaller, higher-cut ones. {premium_clause}, "
        "confirming that price is jointly explained by size and quality "
        "features rather than size alone."
    )


def build_app(df) -> Dash:
    """Construct the single-page Dash application.

    Args:
        df: Cleaned diamonds DataFrame.

    Returns:
        A configured Dash app instance, not yet run.
    """
    app = Dash(__name__)
    animated_fig = build_animated_price_scatter_figure(df)
    conclusion_text = build_conclusion_text(df)

    app.layout = html.Div(
        style={
            "fontFamily": "Helvetica, Arial, sans-serif",
            "maxWidth": "1100px",
            "margin": "0 auto",
            "padding": "24px",
        },
        children=[
            html.H1(RESEARCH_QUESTION, style={"textAlign": "center"}),
            html.P(
                conclusion_text,
                style={
                    "textAlign": "center",
                    "fontSize": "16px",
                    "color": "#333333",
                    "maxWidth": "850px",
                    "margin": "16px auto 32px auto",
                },
            ),
            html.H2("Price vs. Carat Weight, by Cut Grade"),
            html.Img(src="/assets/carat_vs_price.png", style=IMG_STYLE),
            html.H2("Price Distribution by Clarity Grade"),
            html.Img(src="/assets/price_by_clarity.png", style=IMG_STYLE),
            html.H2("Correlation Between Numeric Features"),
            html.Img(
                src="/assets/correlation_heatmap.png",
                style={**IMG_STYLE, "maxWidth": "700px"},
            ),
            html.H2("Interactive Explorer: Price vs. Carat, Animated by Cut"),
            dcc.Graph(figure=animated_fig, config={"displayModeBar": False}),
        ],
    )
    return app


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        The parsed argument namespace.
    """
    parser = argparse.ArgumentParser(
        description="Run the diamonds pricing Dash dashboard."
    )
    add_input_argument(parser)
    parser.add_argument(
        "--host",
        type=str,
        default="127.0.0.1",
        help="Host to serve the dashboard on.",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8050,
        help="Port to serve the dashboard on.",
    )
    return parser.parse_args()


def main() -> None:
    """Load data, build the dashboard, and run the Dash development server."""
    args = parse_args()
    raw_df = load_data(args.input)
    df = clean_data(raw_df)
    app = build_app(df)
    app.run(host=args.host, port=args.port, debug=False)


if __name__ == "__main__":
    main()
